### ISSUE TITLE
Licensing tag in composer.json

### ISSUE THREAD

**Issue by AlessandroMenti** [edvler/yii2-adldap-module#14]
Hi,
I have noticed that you, when you updated the extension to ADLdap 2 v6 (commit 62b56c89b82b0e41967483c9f1e3b765015b585a), you have also changed the license to GPLv3+ (in `composer.json`).

Could you please clarify if that is intended or, on the contrary, if you meant to change the license to LGPLv3+ (the same type used by the previous version) but typed just `GPL` (instead of `LGPL`) by mistake?

**Comment by edvler** [comment]
Hi,

thanks for your question! It was no mistake that i changed from LGPL to GPL.
I think you are using the library in a closed source application and don't want to publish your code?

I'am thinking about chaning back to LGPL....
I know it's no easy for a company to observe the GPL restrictions.

Would this be a solution for you?

Greets

**Comment by AlessandroMenti** [comment]
Hi,
you are correct, I used a previous version of the library in a closed source application at the company I work for (it might be open sourced in the future, but there are no definite plans to do so at this time).

A license change of the module to LGPL would be welcomed.

**Comment by edvler** [comment]
Hi,

I will change the license in the next week.
I've to read a litte bit about the licence subject.

In my opinion also a BSD license maybe suitable, but I don't know the the pro/cons about BSD licenses and LGPL.

The next version would be usable for closed source applications.

Thanks for your open discussion about the license type. I think most peoples don't care about that.

Greets

**Comment by AlessandroMenti** [comment]
You're welcome!

Regarding the pros and cons of the BSD/MIT-style licenses vs. the LGPL, [you might find this page helpful](https://choosealicense.com/licenses/).

In short, the LGPL:
* requires any modifications made to your library to be documented and licensed under the same license (or the GPL);
* requires the source code of you library to be distributed alongside with the application which is using it (the application itself does not need to be licensed under the GPL or otherwise open sourced).

A BSD/MIT-style license, on the contrary, just requires the license text to be distributed with the source code (or the binaries, in the case of compiled software).
