### ISSUE TITLE
Creating new OU

### ISSUE THREAD

**Issue by Shaeldon** [edvler/yii2-adldap-module#18]
Is there a way to create a new OU? Also how could I set the base OU?

Best Regards,
Shael

**Comment by edvler** [comment]
Hello,

please look into the the configuration section, for instructions how to set the base OU.
https://github.com/edvler/yii2-adldap-module/blob/master/readme.md#configuration

As the yii2-adldap-module is only a wrapper for Adldap2, documentation for tasks like creating oder deleting a OU are has to be searched there.

I would try the following to create a OU (untested):
```php
$ou = $ldapObject = \Yii::$app->ad->make()->ou([
    'name' => 'Workstation Computers TEST',
]);
$ou->save();
```
Or other methods listet in https://github.com/Adldap2/Adldap2/blob/v8.0/docs/models/ou.md

**Comment by Shaeldon** [comment]
Thanks a lot already.

1) Is there a way to set the base OU dynamicly? Like giving a the config array to getProvider() directly?

2) Is there a way to get a complete Stacktrace when an operation fails? "ldap_add(): Add: Operations error" Is not 100% helpfull ;)

So long
Shael

**Comment by edvler** [comment]
Hello,

sorry for my late answer.

1. If you need to set your base OU dynamicly, you have to add a new provider to the Adldap instance.
The Aldap instance of the yii2-adldap-module is accessible with \Yii::$app->ad->adLdapInstance.

To add a instance everywhere in the yii2 framework you could try the following code:
```php
//...
        $base_ou = 'dc=example,dc=lan';
        $providerName = 'custprovider';
        $config = [
                // Your account suffix, for example: matthias.maderer@example.lan
                'account_suffix'        => '@example.lan',

                // You can use the host name or the IP address of your controllers.
                'domain_controllers'    => ['srv1', 'srv2'],

                // Your base DN. This is usually your account suffix.
                'base_dn'               => $base_ou,

                // The account to use for querying / modifying users. This
                // does not need to be an actual admin account.
                'admin_username'        => 'user_to_connect',
                'admin_password'        => 'password!',

                // To enable SSL/TLS read the docs/SSL_TLS_AD.md and uncomment
                // the variables below
                //'port' => 636,
                //'use_ssl' => true,
                //'use_tls' => true,                                
            ];
        
        
        
        \Yii::$app->ad->adLdapInstance->addProvider($config, $providerName);
        \Yii::$app->ad->adLdapInstance->connect($providerName);
        
		//Now you can work with getProvider ...
        $ldapObject = \Yii::$app->ad->getProvider('custprovider')->search()->findBy('sAMAccountname', 'matthias');
//...
```

2. The ldap_add() function is provided by PHP itself. I don't know how to debug this function.
Maybe you start at http://php.net/manual/de/function.ldap-add.php for further investigation.

Greets
Matthias
