### ISSUE TITLE
AdLdap 5 dependency is wrong

### ISSUE THREAD

**Issue by vitalyzhakov** [edvler/yii2-adldap-module#8]
My composer config

```
"minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "*",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "alexanderk23/hybrid-xml-parser": "dev-master",
        "domru/console-api-client": "dev-master",
        "domru/counter-memcache": "dev-master",
        "nex/yii2-chosen": "dev-master",
        "edvlerblog/yii2-adldap-module": "v1.0.1",
        "nterms/yii2-pagesize-widget": "*"
    },
```

After run composer update

```
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)             
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for edvlerblog/yii2-adldap-module v1.0.1 -> satisfiable by edvlerblog/yii2-adldap-module[v1.0.1].
    - edvlerblog/yii2-adldap-module v1.0.1 requires adldap/adldap 5.* -> no matching package found.
```

I have read, thad adldap module no longer mainteined.
But community forked and I found https://github.com/Adldap2/Adldap2D
Does it shall be dependency of this component?

**Comment by vitalyzhakov** [comment]
@edvler , may be you share write access?

**Comment by edvler** [comment]
Good morning,

i added you as collaborator to the repository.

Greets
Matthias

Am 11.01.2016 um 13:56 schrieb vitalyzhakov:

**Comment by alexeevdv** [comment]
@vitalyzhakov, since yii2-adldap-module is just a proxy class... you can easily implement it by yourself. Like i did after some time spended to make this extension work :) You can try my implementation with fixed dependencies at https://github.com/alexeevdv/yii2-adldap or create your own. Good luck!

**Comment by vitalyzhakov** [comment]
@alexeevdv , how about testing?
How about users, who prefer dist?
How about packagist?

You are right, I can write several code strings.
But I see, many users find this extension and I is one of them.

**Comment by alexeevdv** [comment]
@vitalyzhakov There is not a big deal to create your own packagist package :)
